### ISSUE TITLE
Proposed change: allow irods_environment.json to override default settings

### ISSUE THREAD

**Issue by stsnel** [snakemake/snakemake-storage-plugin-irods#4]
In the current version of the iRODS storage plugin, default setting values other than `None` have priority over configured settings in the `irods_environment.json` file. For example: even if `irods_environment.json` has  `irods_authentication_scheme` set to `pam`, the plugin will still use `native` (the default value in `StorageProviderSettings`).

I think it would be useful to have the plugin always use settings in the environment file, so that users don't have to copy settings from the iRODS environment file to (for example) the Snakefile. This could either be default behaviour or could be controlled by a boolean plugin setting that controls whether or not iRODS environment file settings have priority. 

If this proposed change is okay, I'd be happy to submit a PR.

**Comment by johanneskoester** [comment]
Yes, I completely agree. Looking forward to your PR! Also, would you be interested to become an official maintainer of this plugin?

**Comment by stsnel** [comment]
Thanks, I'd be happy to help out with maintaining the plugin where I can. 

I expect to be able to send a PR for this change shortly.
